import { cn } from "@/lib/utils";

/**
 * Provider mix — how many assets each provider produced.
 *
 * This is a magnitude comparison across a handful of named categories, which is
 * one series, so it takes one hue rather than a categorical palette. Colour
 * here would only restate the axis label.
 *
 * Built as a real <table> rather than with a charting library: it's a few rows,
 * the markup is the accessible fallback for free, and it keeps a ~190KB
 * dependency out of the analytics route. Bars are horizontal so long provider
 * names read straight instead of rotated.
 */
export function ProviderChart({
  data,
  className,
}: {
  data: Record<string, number>;
  className?: string;
}) {
  const rows = Object.entries(data)
    .map(([name, value]) => ({ name, value }))
    .sort((a, b) => b.value - a.value);

  const total = rows.reduce((sum, r) => sum + r.value, 0);
  const max = Math.max(...rows.map((r) => r.value), 1);

  if (rows.length === 0) {
    return <p className="text-sm text-muted-foreground">No generations yet.</p>;
  }

  return (
    <table className={cn("w-full border-collapse text-sm", className)}>
      <caption className="sr-only">
        Assets generated by provider, {total} in total
      </caption>
      <thead className="sr-only">
        <tr>
          <th scope="col">Provider</th>
          <th scope="col">Assets</th>
          <th scope="col">Share</th>
        </tr>
      </thead>
      <tbody>
        {rows.map((r) => {
          const pct = total > 0 ? (r.value / total) * 100 : 0;
          return (
            <tr key={r.name} className="group">
              <th
                scope="row"
                className="w-px whitespace-nowrap py-2 pe-4 text-start font-mono text-xs font-normal text-muted-foreground"
              >
                {r.name}
              </th>
              <td className="py-2">
                {/* The track gives the bar a length to be read against. */}
                <div className="h-6 w-full rounded-sm bg-muted">
                  <div
                    className="h-full rounded-sm bg-accent transition-[width] duration-500 ease-out"
                    style={{ width: `${Math.max((r.value / max) * 100, 1.5)}%` }}
                  />
                </div>
              </td>
              <td className="w-px whitespace-nowrap py-2 ps-4 text-end">
                {/* Values are direct-labelled, so the bar never has to be
                    measured against a gridline. Text keeps text tokens. */}
                <span className="tabular font-mono text-xs text-foreground">{r.value}</span>
                <span className="tabular ms-2 font-mono text-xs text-muted-foreground">
                  {pct.toFixed(0)}%
                </span>
              </td>
            </tr>
          );
        })}
      </tbody>
    </table>
  );
}
