"use client";

import { useState } from "react";
import Link from "next/link";
import {
  ArrowUpRight,
  Check,
  Copy,
  FileCheck2,
  Fingerprint,
  Search,
  ShieldAlert,
  ShieldCheck,
  Sparkles,
} from "lucide-react";

import { cn } from "@/lib/utils";
import type { PerceptualMatch, VerifyResult } from "@/lib/types";
import { Badge } from "./ui/badge";
import { Card, CardContent } from "./ui/card";

function formatDate(iso?: string | null): string | null {
  if (!iso) return null;
  const d = new Date(iso);
  return Number.isNaN(d.getTime())
    ? null
    : d.toLocaleString(undefined, {
        year: "numeric",
        month: "short",
        day: "numeric",
        hour: "2-digit",
        minute: "2-digit",
      });
}

function CopyHash({ value }: { value: string }) {
  const [copied, setCopied] = useState(false);
  return (
    <button
      type="button"
      onClick={() => {
        void navigator.clipboard?.writeText(value).then(() => {
          setCopied(true);
          setTimeout(() => setCopied(false), 1600);
        });
      }}
      className="inline-grid size-6 shrink-0 place-items-center rounded text-muted-foreground transition-colors hover:bg-secondary hover:text-foreground"
      aria-label={copied ? "Hash copied" : "Copy full hash"}
    >
      {copied ? <Check className="size-3.5 text-verified" /> : <Copy className="size-3.5" />}
    </button>
  );
}

/** One row of the record. Hashes wrap rather than truncate — this is the evidence. */
function Row({
  label,
  children,
}: {
  label: string;
  children: React.ReactNode;
}) {
  return (
    <div className="grid grid-cols-[8rem_minmax(0,1fr)] items-start gap-3 px-4 py-2.5">
      <dt className="label pt-0.5 text-muted-foreground">{label}</dt>
      <dd className="min-w-0 font-mono text-xs">{children}</dd>
    </div>
  );
}

/**
 * The verification certificate.
 *
 * Reads as a record rather than a status card: the verdict up top, then every
 * field that backs it, in mono, with the full hash shown rather than truncated —
 * a visitor checking a claim needs the evidence, not a summary of it. Lineage is
 * a link, so following a generated asset back to its authentic original is one
 * click rather than a copy-paste.
 */
export function VerifyPanel({ result }: { result: VerifyResult }) {
  const tampered = result.content_bound === false;
  const created = formatDate(result.created_at);

  // Verify in the Wild: no cryptographic provenance survived, but the pixels match a known
  // asset — a re-encoded marketplace copy. A distinct, deliberately non-green tier (info, not
  // verified): this is a visual-similarity claim, and the whole card is built to read as
  // evidence rather than the byte-exact guarantee the cryptographic verdict makes.
  if (!result.found && !result.embedded && result.perceptual) {
    return <PerceptualPanel result={result} match={result.perceptual} />;
  }

  if (!result.found && !result.embedded) {
    return (
      <Card>
        <CardContent className="flex items-start gap-3 p-5">
          <span className="mt-0.5 grid size-9 shrink-0 place-items-center rounded-md border bg-muted text-muted-foreground">
            <Search className="size-4" />
          </span>
          <div className="min-w-0">
            <p className="font-semibold tracking-tight">No record for this hash</p>
            <p className="mt-1 text-sm text-muted-foreground">
              Nothing in the ledger matches it, and the file carries no embedded manifest. It
              wasn&apos;t produced by OriginShot — or it was re-encoded, which breaks the binding.
            </p>
            <p className="mt-3 break-all font-mono text-xs text-muted-foreground">
              {result.sha256}
            </p>
          </div>
        </CardContent>
      </Card>
    );
  }

  const verdict = tampered
    ? {
        icon: ShieldAlert,
        title: "Content has been altered",
        sub: "The bytes no longer match the manifest",
        cls: "border-danger/25 bg-danger-surface text-danger",
      }
    : result.verified
      ? {
          icon: result.is_authentic ? ShieldCheck : Sparkles,
          title: "Integrity verified",
          sub: result.is_authentic ? "Authentic original" : "AI-generated by OriginShot",
          cls: "border-verified/25 bg-verified-surface text-verified",
        }
      : {
          icon: ShieldAlert,
          title: "Manifest could not be verified",
          sub: "A record exists, but its signature didn't check out",
          cls: "border-warning/25 bg-warning-surface text-warning",
        };

  const Icon = verdict.icon;

  return (
    <Card className="overflow-hidden">
      {/* Verdict — icon + text + colour, never colour alone. */}
      <div className={cn("flex items-center gap-3 border-b p-5", verdict.cls)}>
        <span className="grid size-10 shrink-0 place-items-center rounded-md bg-card/60">
          <Icon className="size-5" />
        </span>
        <div className="min-w-0">
          <p className="font-semibold tracking-tight">{verdict.title}</p>
          <p className="truncate text-sm opacity-90">{verdict.sub}</p>
        </div>
      </div>

      <div className="flex flex-wrap gap-2 border-b p-4">
        <Badge variant={result.verified ? "verified" : "warning"} size="sm">
          <ShieldCheck />
          {result.verified ? "Manifest valid" : "Manifest invalid"}
        </Badge>
        {result.content_bound === true && (
          <Badge variant="verified" size="sm">
            <FileCheck2 /> Content-bound
          </Badge>
        )}
        {tampered && (
          <Badge variant="danger" size="sm">
            <ShieldAlert /> Tampered
          </Badge>
        )}
        {result.embedded && (
          <Badge variant="outline" size="sm">
            <FileCheck2 /> Manifest embedded
          </Badge>
        )}
        {result.modality && (
          <Badge variant="outline" size="sm">
            {result.modality}
          </Badge>
        )}
      </div>

      <dl className="divide-y">
        <Row label="sha256">
          <span className="flex items-start gap-1.5">
            <span className="min-w-0 break-all">{result.sha256}</span>
            <CopyHash value={result.sha256} />
          </span>
        </Row>

        {result.parent_sha256 && (
          <Row label="derived from">
            {/* Lineage is navigable — the point of a chain is following it. */}
            <Link
              href={`/verify/${result.parent_sha256}`}
              className="inline-flex items-start gap-1 break-all t-accent underline decoration-accent/30 underline-offset-4 hover:decoration-accent"
            >
              <span className="min-w-0 break-all">{result.parent_sha256}</span>
              <ArrowUpRight className="mt-px size-3.5 shrink-0" />
            </Link>
          </Row>
        )}

        {result.style && <Row label="style">{result.style}</Row>}
        {result.provider && <Row label="provider">{result.provider}</Row>}
        {result.model && <Row label="model">{result.model}</Row>}
        {created && <Row label="created">{created}</Row>}

        {/* Position in the append-only log. Shown only when present: absence proves
            nothing (appends are best-effort), so rendering a "not logged" row would
            invent a negative signal the data doesn't support. */}
        {result.ledger && (
          <Row label="log entry">
            <span className="flex flex-wrap items-baseline gap-x-2">
              <span className="tabular">
                #{result.ledger.seq} of {result.ledger.log_size}
              </span>
              {result.ledger.checkpoint_covers_entry ? (
                <Link
                  href="/ledger"
                  className="t-accent underline decoration-accent/30 underline-offset-4 hover:decoration-accent"
                >
                  covered by checkpoint {result.ledger.checkpoint_hash?.slice(0, 12)}…
                </Link>
              ) : (
                <span className="text-muted-foreground">
                  not yet in a published checkpoint
                </span>
              )}
            </span>
          </Row>
        )}
      </dl>

      <p
        className={cn(
          "border-t p-4 text-sm",
          tampered ? "bg-danger-surface text-danger" : "bg-muted/50 text-muted-foreground",
        )}
      >
        {result.disclosure}
      </p>
    </Card>
  );
}

/**
 * Verify in the Wild — the perceptual-match tier.
 *
 * Shown when a file carries no surviving manifest and matches no stored hash, yet looks like
 * a known asset: the fingerprint of a marketplace that re-encoded the image and stripped its
 * provenance. Rendered in the `info` tone, never `verified`, and every line insists on the
 * distinction — this is a *visual likeness*, offered as evidence, not the byte-exact proof
 * the cryptographic verdict makes. The raw bit-distance is always on screen so the strength
 * of the claim is legible, not hidden behind a single confidence number.
 */
function PerceptualPanel({
  result,
  match,
}: {
  result: VerifyResult;
  match: PerceptualMatch;
}) {
  return (
    <Card className="overflow-hidden">
      <div className="flex items-center gap-3 border-b border-info/25 bg-info-surface p-5 text-info">
        <span className="grid size-10 shrink-0 place-items-center rounded-md bg-card/60">
          <Fingerprint className="size-5" />
        </span>
        <div className="min-w-0">
          <p className="font-semibold tracking-tight">
            {match.strong ? "Perceptual match" : "Possible perceptual match"}
          </p>
          <p className="truncate text-sm opacity-90">
            Looks like an OriginShot asset — evidence, not cryptographic proof
          </p>
        </div>
      </div>

      <div className="flex flex-wrap gap-2 border-b p-4">
        <Badge variant="info" size="sm">
          <Fingerprint /> Visual match {match.distance}/64
        </Badge>
        <Badge variant="outline" size="sm">
          manifest stripped
        </Badge>
        {match.matched_in_ledger && (
          <Badge variant="outline" size="sm">
            <FileCheck2 /> match is in the ledger
          </Badge>
        )}
      </div>

      <dl className="divide-y">
        <Row label="uploaded">
          <span className="flex items-start gap-1.5">
            <span className="min-w-0 break-all text-muted-foreground">{result.sha256}</span>
            <CopyHash value={result.sha256} />
          </span>
        </Row>

        <Row label="matches">
          <Link
            href={`/verify/${match.matched_sha256}`}
            className="inline-flex items-start gap-1 break-all t-accent underline decoration-accent/30 underline-offset-4 hover:decoration-accent"
          >
            <span className="min-w-0 break-all">{match.matched_sha256}</span>
            <ArrowUpRight className="mt-px size-3.5 shrink-0" />
          </Link>
        </Row>

        <Row label="distance">
          {/* Raw evidence first, the friendly number second — never the reverse. */}
          <span className="flex flex-wrap items-baseline gap-x-2">
            <span className="tabular">{match.distance} / 64 bits</span>
            <span className="text-muted-foreground">
              ({Math.round(match.confidence * 100)}% confidence)
            </span>
          </span>
        </Row>

        {match.parent_sha256 && (
          <Row label="authentic original">
            <Link
              href={`/verify/${match.parent_sha256}`}
              className="inline-flex items-start gap-1 break-all t-accent underline decoration-accent/30 underline-offset-4 hover:decoration-accent"
            >
              <span className="min-w-0 break-all">{match.parent_sha256}</span>
              <ArrowUpRight className="mt-px size-3.5 shrink-0" />
            </Link>
          </Row>
        )}

        {match.style && <Row label="style">{match.style}</Row>}
        {match.provider && <Row label="provider">{match.provider}</Row>}
        {match.model && <Row label="model">{match.model}</Row>}
      </dl>

      <p className="border-t bg-info-surface/40 p-4 text-sm text-muted-foreground">
        {result.disclosure}
      </p>
    </Card>
  );
}
