"use client";

import Link from "next/link";
import { ShieldCheck } from "lucide-react";

import { cn } from "@/lib/utils";
import { DEMO_ASSETS } from "@/lib/demo-assets";

/**
 * The signature element.
 *
 * A photographer's contact sheet, printed from a real OriginShot run: every
 * frame below is genuine output stored in Backblaze B2, and the hash under each
 * one is that asset's true SHA-256. They are links — click any frame and /verify
 * resolves the hash against the ledger. The proof on this page is checkable
 * rather than claimed, which is the whole argument the product makes.
 */

const SHEET = [
  "studio-01",
  "lifestyle-02",
  "studio-03",
  "lifestyle-05",
  "scene-02",
  "studio-04",
  "lifestyle-04",
  "lifestyle-01",
] as const;

export function ContactSheet({ className }: { className?: string }) {
  const frames = SHEET.map((slot) => DEMO_ASSETS.find((a) => a.slot === slot)).filter(
    (a): a is (typeof DEMO_ASSETS)[number] => Boolean(a),
  );

  return (
    <figure className={cn("min-w-0", className)}>
      <div className="overflow-hidden rounded-lg border bg-card shadow-float">
        {/* Rebate strip — the legend printed along a real sheet's edge. */}
        <div className="flex items-center justify-between gap-3 border-b bg-muted/60 px-3 py-2">
          <span className="label-mono truncate text-muted-foreground">
            Pack 001 · Ceramic mug · {frames.length} frames
          </span>
          <span className="label-mono hidden shrink-0 items-center gap-1.5 text-verified sm:inline-flex">
            <ShieldCheck className="size-3" />
            SHA-256 bound
          </span>
        </div>

        <div className="grid grid-cols-2 gap-px bg-border sm:grid-cols-4">
          {frames.map((a, i) => (
            <Link
              key={a.slot}
              href={`/verify/${a.sha}`}
              className="group relative block bg-card focus-visible:z-10"
              aria-label={`Verify the ${a.style} frame, hash ${a.sha.slice(0, 12)}`}
            >
              {/* Frames are uniform, as on a real sheet — the eye compares the
                  subject, not the crop. Source ratios vary, so object-cover. */}
              <div className="relative aspect-square overflow-hidden">
                {/* eslint-disable-next-line @next/next/no-img-element */}
                <img
                  src={a.src}
                  alt={`${a.style} product shot generated by OriginShot from a single source photo`}
                  width={a.width}
                  height={a.height}
                  className="size-full object-cover transition-transform duration-500 ease-out group-hover:scale-[1.04]"
                  loading={i < 4 ? "eager" : "lazy"}
                  fetchPriority={i < 2 ? "high" : "auto"}
                />
                {/* Frame index, set like a sprocket number. */}
                <span className="label-mono absolute start-1.5 top-1.5 rounded bg-black/55 px-1 py-0.5 text-white/90 backdrop-blur-sm">
                  {String(i + 1).padStart(2, "0")}
                </span>
              </div>

              {/* The hash is the point: it's real, and it resolves. */}
              <span className="flex items-center justify-between gap-1 border-t px-2 py-1.5">
                <span className="truncate font-mono text-[10px] text-muted-foreground transition-colors group-hover:text-foreground">
                  {a.sha.slice(0, 12)}
                </span>
                <ShieldCheck className="size-3 shrink-0 text-muted-foreground/50 transition-colors group-hover:text-verified" />
              </span>
            </Link>
          ))}
        </div>
      </div>

      <figcaption className="mt-3 text-xs text-muted-foreground">
        Real output from one source photo, served from Backblaze B2. Every hash is live — open a
        frame to check it against the provenance ledger.
      </figcaption>
    </figure>
  );
}
