"use client";

import { useState } from "react";
import Link from "next/link";

import { cn } from "@/lib/utils";
import { DEMO_ASSETS } from "@/lib/demo-assets";
import { Section } from "./section";

/**
 * What actually comes back from a run, grouped the way a seller thinks about it:
 * by where the picture is going to be used. Switching a tab swaps real frames
 * from the same source photo, which is the point — one object, many contexts.
 */
const GROUPS = [
  {
    id: "studio",
    label: "Studio",
    blurb:
      "Clean white-background shots that satisfy Amazon and eBay's main-image rules without a lightbox or a tripod.",
    slots: ["studio-01", "studio-02", "studio-03", "studio-04"],
  },
  {
    id: "lifestyle",
    label: "Lifestyle",
    blurb:
      "The product in a room someone recognises. This is what earns the click on Etsy and Instagram.",
    slots: ["lifestyle-02", "lifestyle-05", "lifestyle-04", "lifestyle-01"],
  },
  {
    id: "scene",
    label: "In context",
    blurb:
      "Desk, café, and kitchen scenes for listing galleries, where a buyer is working out how big the thing actually is.",
    slots: ["scene-01", "scene-02", "lifestyle-03", "lifestyle-06"],
  },
  {
    id: "motion",
    label: "Motion",
    blurb:
      "A five-second turntable generated from the same photo — the clip marketplaces now push hardest in search.",
    slots: ["video-01"],
  },
] as const;

export function PackShowcase() {
  const [active, setActive] = useState<string>(GROUPS[0].id);
  const group = GROUPS.find((g) => g.id === active) ?? GROUPS[0];
  const frames = group.slots
    .map((slot) => DEMO_ASSETS.find((a) => a.slot === slot))
    .filter((a): a is (typeof DEMO_ASSETS)[number] => Boolean(a));

  return (
    <Section
      eyebrow="One source photo"
      title="Every frame below came from the same mug"
      description="No second shoot, no reshoot for each marketplace. The object stays consistent because the pipeline reads it once and holds onto it."
    >
      <div className="mt-10 flex flex-wrap gap-2" role="tablist" aria-label="Pack contents">
        {GROUPS.map((g) => {
          const on = g.id === active;
          return (
            <button
              key={g.id}
              role="tab"
              aria-selected={on}
              onClick={() => setActive(g.id)}
              className={cn(
                "rounded-full border px-4 py-1.5 text-sm font-medium transition-colors",
                on
                  ? "border-transparent bg-primary text-primary-foreground"
                  : "bg-card text-muted-foreground hover:bg-secondary hover:text-foreground",
              )}
            >
              {g.label}
            </button>
          );
        })}
      </div>

      <p className="mt-5 max-w-xl text-sm text-muted-foreground">{group.blurb}</p>

      <div
        className={cn(
          "mt-6 grid gap-3 sm:gap-4",
          // The clip stands alone rather than being squeezed into a four-up.
          group.id === "motion"
            ? "max-w-md grid-cols-1"
            : "grid-cols-2 lg:grid-cols-4",
        )}
      >
        {frames.map((a) =>
          a.style === "video" ? (
            <figure key={a.slot} className="frame min-w-0 overflow-hidden rounded-md border bg-muted">
              <div className="aspect-square">
                {/* eslint-disable-next-line jsx-a11y/media-has-caption */}
                <video
                  src={a.src}
                  className="size-full object-cover"
                  autoPlay
                  muted
                  loop
                  playsInline
                  preload="none"
                  aria-label="Five-second product turntable generated by OriginShot"
                />
              </div>
            </figure>
          ) : (
            <figure
              key={a.slot}
              className="frame min-w-0 overflow-hidden rounded-md border bg-muted"
            >
              <div className={cn(a.style === "studio" ? "aspect-square" : "aspect-[4/5]")}>
                {/* eslint-disable-next-line @next/next/no-img-element */}
                <img
                  src={a.src}
                  alt={`${group.label} frame generated by OriginShot`}
                  width={a.width}
                  height={a.height}
                  className="size-full object-cover"
                  loading="lazy"
                />
              </div>
            </figure>
          ),
        )}
      </div>

      {group.id === "motion" && (
        // The provenance point lands hardest here: a 4MB MP4 that still passes
        // byte-level verification is the least expected part of the demo.
        <p className="mt-4 max-w-md text-xs text-muted-foreground">
          Produced by{" "}
          <span className="font-mono">Kling-Image2Video-V2.1-Master</span> in 4m 14s. The file
          carries an embedded manifest and still verifies byte-for-byte —{" "}
          <Link
            href={`/verify/${frames[0]?.sha ?? ""}`}
            className="text-accent underline decoration-accent/30 underline-offset-4 hover:decoration-accent"
          >
            check it
          </Link>
          .
        </p>
      )}
    </Section>
  );
}
